channel_indexers:
  # TG-CHANNEL-ID_MYINDEXER: MyIndexer
  # "1234567890": MyIndexer

group_topic_indexers:
  # TG-GROUP-TOPIC-ID_MYINDEXER: MyIndexer
  # "1234567890_1234": MyIndexer

chat_indexers:
  # TG-CHAT-ID_MYINDEXER: MyIndexer
  # "1234567890": MyIndexer
